spring.datasource.url=jdbc:postgresql://localhost:5433/reviewpilot
spring.datasource.username=reviewpilot
spring.datasource.password=reviewpilot

spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true